# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 03:58
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zhihudaiguang',
            fields=[
                ('imageurl', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), size=None)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_vote_up', models.BooleanField(default=False)),
                ('is_sex', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('data_score', models.FloatField()),
            ],
        ),
    ]
