# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-06 04:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachong', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lives',
            fields=[
                ('live', django.contrib.postgres.fields.jsonb.JSONField()),
                ('subject', models.TextField()),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
