# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 03:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pachong', '0002_lives'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhihudaiguang',
            name='xiaobing',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=[]),
        ),
    ]
