# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-08 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachong', '0006_zhihudaiguang_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhihudaiguang',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
    ]
