# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-09 03:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pachong', '0007_zhihudaiguang_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='zhihudaiguang',
            name='fs',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=[], size=None),
        ),
    ]
